apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pto-management-service.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "pto-management-service.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "pto-management-service.name" . }}
    spec:
      nodeSelector:
        pubsub: "true"
      serviceAccountName: eks-apps-service-account
      initContainers:
        - name: migrate
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "sh", "-c" ]
          args:
            - |
              echo "Running makemigrations and migrate for PTO...";
              python manage.py makemigrations --noinput && python manage.py migrate --noinput
          envFrom:
            - configMapRef:
                name: pto-config
            - secretRef:
                name: pto-secrets
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: pto-config
            - secretRef:
                name: pto-secrets
