apiVersion: v1
kind: Secret
metadata:
  name: pto-secrets
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | b64enc | quote }}
  DB_USER: "cG9zdGdyZXM="
  DB_PASSWORD: "VGltZXNoZWV0REJQVw=="
