apiVersion: v1
kind: Secret
metadata:
  name: pto-secrets
type: Opaque
data:
  DJANGO_SECRET_KEY: {{ .Values.secrets.djangoSecretKey | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}

