replicaCount: 3
nameOverride: "pto-management-service"

image:
  repository: your-docker-hub-id/your-image-name
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8000

secrets:
  djangoSecretKey: "your-actual-django-secret"
  dbPassword: "your-db-password"
